### ISSUE TITLE
Hosting with travis-ci

### ISSUE THREAD

**Issue by AmbiTyga** [bchiang7/v2#2]
Well I am trying to host the repo with travis-ci
Please instruct me with the travis.yml for what should I add in it and please kindly give some time as I am not a developer

**Comment by sn1f3rt** [comment]
@AmbiTyga Travis-ci is not a host, it's just a medium for checking whether your application builds as you want or not. 

If you would like to host something, you need either something like Netlify or GitHub Pages, or a VPS. Netlify may be free, but quite complicated for beginners, hence, I don't recommend it as such. 

I'm myself a VPS provider, so if you'd like a cheap one, drop me an email and I can help you set this up as well. :-)

**Comment by AmbiTyga** [comment]
Sorry @sohamb03 but I want to go wth github pages. I just want to know, that what should I do So that I could use @bchiang7 repo to make my own github page.
In the getting started section, all the methods enlisted there, how do I have to use that

**Comment by sn1f3rt** [comment]
Well sorry for the confusion but you can't use GitHub pages here, as per https://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages - since GitHub Pages only host static HTML. 

You'll have to find a way to publish it to Netlify instead, which is free too, but since I don't use it I can't help with that.

**Comment by AmbiTyga** [comment]
@sohamb03  Thanks friend
